# 开发环境配置
server:
  port: 2580
spring:

  #profiles: prod
  mqtt:
    broker:

      # broker唯一标识
      id: mqtt-broker-1
      # SSL端口
      ssl-port: 8885
      # SSL密钥文件密码
      ssl-password: 123456
      # MQTT 端口
      mqtt-port: 1883
      #
      auth-type: 1
      #
      use-ssl: false
      # websocket端口
      websocket-ssl-port: 9995
      # websocket path 值
      websocket-path: /mqtt
      # 心跳时间(秒)
      keep-alive: 60
      # 开启Epoll模式, linux下建议开启
      use-epoll: false
      # 开启组播方式集群
      enable-multicast-group: true
      # 组播地址
      multicast-group: 239.255.255.255
      cache:
        # 持久化缓存内存初始化大小(MB)
        persistence-initial-size: 64
        # 持久化缓存占用内存最大值(MB)
        persistence-max-size: 128
        # 非持久化缓存内存初始化大小(MB)
        not-persistence-initial-size: 64
        # 非持久化缓存占用内存最大值(MB)
        not-persistence-max-size: 128
        # persistence-store-path: /mqtt-broker/persistence

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html

# 日志 默认是debug
logging:
  level:
    root: info
    com.easyiot.iot.mqtt.server: info

webadmin:
  username:
    admin
  password:
    password

# Spring监控
info:
  head: head
  body: body
management:
        endpoints:

                web:
                        exposure:
                                #加载所有的端点，默认只加载了info、health
                                include: '*'
        endpoint:
                health:
                        show-details: always
                #可以关闭指定的端点
                shutdown:
                        enabled: false
                sessions:
                        enabled:
